apiVersion: v1
kind: Pod
metadata:
  name: spark-perms-test
spec:
  containers:
  - name: spark-perms-test-container
    imagePullPolicy: IfNotPresent
    image: list-directories:latest
    command: ["/bin/sh", "-c", "ls -l /mnt/data01 && sleep 3600"]
    volumeMounts:
      - name: data-volume
        mountPath: /mnt/data01
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: pvc01
