apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: list-directory-01
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  imagePullSecrets:
    - regcred
  image: "registry.digitalocean.com/docrjneirar/list-directory-01"
  imagePullPolicy: IfNotPresent
  mainApplicationFile: "local:///list_directories.py"
  sparkVersion: "3.5.0"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.5.0
    serviceAccount: spark
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.5.0
