# minikube mount D:/data100:/mnt/data100
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv100
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data100"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc100
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
