# minikube mount D:/data20:/mnt/data20
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv20
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data20"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc20
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
