{
 "title": "Spark-metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Porcentaje de Tareas Completadas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(executor_id) (increase(metrics_executor_completedTasks_total{executor_id!=\"driver\"}[5m]))) / (sum by(executor_id) (metrics_executor_totalTasks_total{executor_id!=\"driver\"}))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Porcentaje de Tareas Completadas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by(executor_id) (increase(metrics_executor_completedTasks_total{executor_id!=\"driver\"}[5m]))) / (sum by(executor_id) (metrics_executor_totalTasks_total{executor_id!=\"driver\"}))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uso de CPU por Pod",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"default\"}[5m])) by (pod)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage by Pod",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"default\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Porcentaje de Memoria RAM Utilizada por Spark",
   "type": "stat",
   "gridPos": { "h": 10, "w": 7, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum(metrics_executor_JVMHeapMemory_bytes + metrics_executor_JVMOffHeapMemory_bytes)\r\n  /\r\n  sum(machine_memory_bytes)\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Porcentaje de CPU Utilizado por Spark",
   "type": "stat",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum(rate(container_cpu_usage_seconds_total{namespace=\"default\"}[5m]))\r\n  /\r\n  sum(machine_cpu_cores)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uso de CPU por Pod",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"default\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uso de Memoria por Pod",
   "type": "timeseries",
   "description": "Memory Usage by Pod",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"default\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uso de Memoria del Heap de JVM del Driver",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg_over_time({__name__=~\"metrics_spark_.*_driver_jvm_heap_used_Value\", type=\"gauges\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uso Total de Memoria Heap JVM por Ejecutor",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(executor_id) (metrics_executor_JVMHeapMemory_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memoria Heap para Almacenamiento en Ejecutores",
   "type": "timeseries",
   "description": "Más específico",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(executor_id) (metrics_executor_usedOnHeapStorageMemory_bytes)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tiempo total de Garbage Collection",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum by(executor_id) (metrics_executor_totalGCTime_seconds_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Porcentaje de Tiempo en GC vs Tiempo Total de Ejecución por Ejecutor en Spark",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by(executor_id) (metrics_executor_totalGCTime_seconds_total) / sum by(executor_id) (metrics_executor_totalDuration_seconds_total)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Balance de Carga de Tareas en Ejecutores",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (executor_id) (increase(metrics_executor_completedTasks_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duración Total de Tareas por Ejecutor en Spark",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(executor_id) (metrics_executor_totalDuration_seconds_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total de Tareas por Ejecutor en Spark",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 45 },
   "targets": [
    {
     "expr": "sum by(executor_id) (metrics_executor_totalTasks_total)\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}